### Global Variables
@host = http://localhost:8080
@api = /api/products

### 1. Create a Product
# @name createProduct
POST {{host}}{{api}}
Content-Type: application/json

{
  "name": "Apple MacBook Pro",
  "price": 2500.0
}

### 2. List All Products
GET {{host}}{{api}}

### 3. Get Specific Product (Use ID from Create response)
GET {{host}}{{api}}/1

### 4. Update Product
PUT {{host}}{{api}}/1
Content-Type: application/json

{
  "name": "Apple MacBook Pro M3",
  "price": 2700.0
}

### 5. Delete Product
DELETE {{host}}{{api}}/1

### 6. Verify Deletion
GET {{host}}{{api}}
