package org.example.common;

public enum TraceEventType {
    HTTP_IN_START, HTTP_IN_END, HTTP_OUT,
    MQ_PRODUCE, MQ_CONSUME_START, MQ_CONSUME_END,
    ASYNC_START, ASYNC_END,
    DB_QUERY_START, DB_QUERY_END,
    CACHE_HIT, CACHE_MISS, CACHE_SET, CACHE_DEL, CACHE_ERROR
}
