server.port=8080
spring.application.name=trace-admin

spring.datasource.url=jdbc:postgresql://localhost:5432/trace_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Thymeleaf cache disabled for development
spring.thymeleaf.cache=false
