server.port=8000
spring.application.name=sample-crud-app

# DB Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/trace_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.auto-offset-reset=earliest

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Logging
logging.level.org.example.sample=DEBUG
