server.port=8000
spring.application.name=sample-crud-app

# H2 Console
spring.h2.console.enabled=true

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.auto-offset-reset=earliest

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Logging
logging.level.org.example.sample=DEBUG
